// Flat config, run once from the root across the whole workspace.
//
// Per-package lint scripts would need eslint installed seven times under
// pnpm's strict linking. One root invocation is faster and leaves one config
// to keep correct.

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/coverage/**',
      'site/**',
      'bin/**',
      // Generated from packages/schema — a lint failure here is a generator bug,
      // not something to fix by hand.
      '**/*.gen.ts',
      // Generated by `pnpm db:pull` from the live database. Same reasoning: the
      // fix for a complaint here is a change to the generator or the migration,
      // never an edit to the file, which the next pull would discard anyway.
      'packages/db/src/schema.ts',
      'packages/db/src/relations.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  // Applies to every linted file, JS and TS alike. typescript-eslint's
  // recommended set reaches .mjs too, so scoping this to **/*.ts would leave
  // the build tooling judged by the default options.
  {
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      // Unused args are normal in handler signatures; an underscore marks intent.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          // `const { omitMe: _, ...rest }` is the idiomatic way to drop a key.
          ignoreRestSiblings: true,
        },
      ],
      // This codebase handles security telemetry. `any` erases the type safety
      // that stops a tenant id being confused with a user id.
      '@typescript-eslint/no-explicit-any': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  // Build and planning tooling is expected to write to stdout.
  {
    files: [
      'scripts/**/*.{js,mjs}',
      'tools/**/*.{js,mjs}',
      // Schema tooling that ships with the package it serves, e.g.
      // packages/db/scripts/*.mjs — same role as the root scripts above.
      'packages/*/scripts/**/*.{js,mjs}',
      'eslint.config.js',
    ],
    languageOptions: { globals: globals.node },
    rules: { 'no-console': 'off' },
  },

  // Tests assert on shapes that are deliberately wrong.
  {
    files: ['**/*.test.{ts,tsx}', '**/__tests__/**'],
    rules: { '@typescript-eslint/no-non-null-assertion': 'off' },
  },

  // packages/ui is the only React code in the repo so far — hook rules scoped
  // here rather than loaded globally for packages that never use a hook.
  {
    files: ['packages/ui/src/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },

  // P0-08 AC1: no hardcoded hex colour anywhere in packages/ui. Every colour
  // must come through a design token (a Tailwind utility class generated from
  // one, or a value imported from @sentinel/design-tokens) so the token
  // package stays the single place a colour decision can be changed. Scoped
  // to packages/ui/src only — @sentinel/design-tokens itself is where hex
  // values are legitimately defined, and this rule would be nonsensical there.
  {
    files: ['packages/ui/src/**/*.{ts,tsx}'],
    plugins: {
      'control-room': {
        rules: {
          'no-hardcoded-hex': {
            meta: {
              type: 'problem',
              docs: {
                description: 'disallow hardcoded hex colours outside @sentinel/design-tokens',
              },
              schema: [],
            },
            create(context) {
              const HEX = /#[0-9a-fA-F]{3,8}\b/;
              return {
                Literal(node) {
                  if (typeof node.value === 'string' && HEX.test(node.value)) {
                    context.report({
                      node,
                      message:
                        'Hardcoded hex colour. Use a Tailwind utility backed by a design ' +
                        'token, or import the value from @sentinel/design-tokens.',
                    });
                  }
                },
                TemplateElement(node) {
                  if (HEX.test(node.value.raw)) {
                    context.report({
                      node,
                      message:
                        'Hardcoded hex colour in a template literal. Use a design token instead.',
                    });
                  }
                },
              };
            },
          },
        },
      },
    },
    rules: { 'control-room/no-hardcoded-hex': 'error' },
  },
);
