package sigmac

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// GenGoPackage is the package name every generated file declares.
const GenGoPackage = "detectgen"

// genHeader is prepended to both generated files — AC: "clearly marked
// as generated". The exact "Code generated ... DO NOT EDIT." phrasing
// is also what gofmt/goimports and golang.org/x/tools' own generated-file
// detection key off, so tooling (and reviewers) recognise it as such for
// free.
func genHeader(source string) string {
	return fmt.Sprintf("// Code generated by %s from detections/rules and detections/fixtures. DO NOT EDIT.\n\n", source)
}

// GenerateSource compiles every rule in rules into Go source: one
// predicate function per rule plus a Rules registry (ruleCode), and one
// table-driven test per rule asserting its fixture's positive case
// matches and its negative case does not (testCode) — this ticket's own
// two required deliverables. Returns an error naming the rule if any
// rule's fixture is missing (AC: "fails if a rule lacks either
// fixture") — MITRE-id absence is already impossible to reach here at
// all, since Parse (P2-01) refuses to produce a Rule without one; T2's
// own test proves that end-to-end through this exact pipeline rather
// than re-asserting P2-01's own unit test.
//
// Both outputs are passed through go/format.Source before being
// returned, which is what makes regeneration byte-identical for
// unchanged inputs (AC/T4) — two independently-built strings that
// happen to differ only in whitespace would otherwise show up as a
// spurious diff every time this runs.
func GenerateSource(rules []*Rule, fixturesDir string) (ruleCode, testCode []byte, err error) {
	sorted := make([]*Rule, len(rules))
	copy(sorted, rules)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Slug < sorted[j].Slug })

	fixtures := make(map[string]*Fixture, len(sorted))
	for _, r := range sorted {
		f, err := LoadFixture(fixturesDir, r.Slug)
		if err != nil {
			return nil, nil, fmt.Errorf("rule %q (%s): %w", r.Title, r.Slug, err)
		}
		fixtures[r.Slug] = f
	}

	var funcs strings.Builder
	var registry strings.Builder
	var tests strings.Builder
	usedStrings, usedRegexp, usedBase64 := false, false, false

	for _, r := range sorted {
		funcName := ruleFuncName(r.Slug)
		body, flags := emitRuleBody(r)
		usedStrings = usedStrings || flags.strings
		usedRegexp = usedRegexp || flags.regexp
		usedBase64 = usedBase64 || flags.base64

		fmt.Fprintf(&funcs, "func %s(ev map[string]string) bool {\n%s\n}\n\n", funcName, body)

		fmt.Fprintf(&registry, "\t{ID: %s, Title: %s, Level: %s, MitreIDs: %s, Engine: %s, Matches: %s},\n",
			strconv.Quote(r.ID), strconv.Quote(r.Title), strconv.Quote(r.Level), goStringSlice(r.MitreIDs), strconv.Quote(r.Engine.String()), funcName)

		f := fixtures[r.Slug]
		fmt.Fprintf(&tests, "func TestRule_%s(t *testing.T) {\n", sanitizeIdent(r.Slug))
		fmt.Fprintf(&tests, "\tif !%s(%s) {\n\t\tt.Fatalf(%s)\n\t}\n", funcName, goEventLiteral(f.Positive), strconv.Quote("positive fixture for rule "+r.Slug+" ("+r.Title+") did not match"))
		fmt.Fprintf(&tests, "\tif %s(%s) {\n\t\tt.Fatalf(%s)\n\t}\n", funcName, goEventLiteral(f.Negative), strconv.Quote("negative fixture for rule "+r.Slug+" ("+r.Title+") matched, but should not have"))
		fmt.Fprintf(&tests, "}\n\n")
	}

	var ruleImports strings.Builder
	ruleImports.WriteString("import (\n")
	if usedStrings {
		ruleImports.WriteString("\t\"strings\"\n")
	}
	if usedRegexp {
		ruleImports.WriteString("\t\"regexp\"\n")
	}
	if usedBase64 {
		ruleImports.WriteString("\t\"encoding/base64\"\n")
	}
	ruleImports.WriteString(")\n\n")

	ruleSrc := genHeader("sigmac-gen") +
		"package " + GenGoPackage + "\n\n" +
		ruleImports.String() +
		"type CompiledRule struct {\n" +
		"\tID       string\n" +
		"\tTitle    string\n" +
		"\tLevel    string\n" +
		"\tMitreIDs []string\n" +
		"\tEngine   string\n" +
		"\tMatches  func(ev map[string]string) bool\n" +
		"}\n\n" +
		"var Rules = []CompiledRule{\n" + registry.String() + "}\n\n" +
		"func boolToInt(b bool) int {\n\tif b {\n\t\treturn 1\n\t}\n\treturn 0\n}\n\n" +
		decodeBase64EqSrc(usedBase64) +
		funcs.String()

	testSrc := genHeader("sigmac-gen") +
		"package " + GenGoPackage + "\n\n" +
		"import \"testing\"\n\n" +
		tests.String()

	formattedRule, err := format.Source([]byte(ruleSrc))
	if err != nil {
		return nil, nil, fmt.Errorf("formatting generated rule code: %w\n--- source ---\n%s", err, ruleSrc)
	}
	formattedTest, err := format.Source([]byte(testSrc))
	if err != nil {
		return nil, nil, fmt.Errorf("formatting generated test code: %w\n--- source ---\n%s", err, testSrc)
	}
	return formattedRule, formattedTest, nil
}

type modifierUsage struct {
	strings, regexp, base64 bool
}

// emitRuleBody emits one rule's predicate function body — a line per
// selection (each an AND of its field expressions, emitted by
// emitFieldExpr) followed by a return of the condition expression over
// those selections' Go variables (emitConditionExpr).
func emitRuleBody(r *Rule) (string, modifierUsage) {
	var b strings.Builder
	var usage modifierUsage

	names := make([]string, 0, len(r.Selections))
	for name := range r.Selections {
		names = append(names, name)
	}
	sort.Strings(names)

	selVar := make(map[string]string, len(names))
	for _, name := range names {
		sel := r.Selections[name]
		v := "sel_" + sanitizeIdent(name)
		selVar[name] = v
		exprs := make([]string, 0, len(sel.Fields))
		for _, fm := range sel.Fields {
			expr, u := emitFieldExpr(fm)
			usage.strings = usage.strings || u.strings
			usage.regexp = usage.regexp || u.regexp
			usage.base64 = usage.base64 || u.base64
			exprs = append(exprs, expr)
		}
		if len(exprs) == 0 {
			exprs = []string{"true"}
		}
		fmt.Fprintf(&b, "\t%s := %s\n", v, strings.Join(exprs, " &&\n\t\t"))
	}

	fmt.Fprintf(&b, "\treturn %s\n", emitConditionExpr(r.Condition, selVar, r.Selections))
	return b.String(), usage
}

// emitFieldExpr emits one FieldMatch as a Go boolean expression, OR'd
// (or, under AllOf, AND'd) across its Values — the compiled mirror of
// interpret.go's evaluateFieldMatch, over the SAME ev map[string]string
// an interpreted Rule would read.
func emitFieldExpr(fm FieldMatch) (string, modifierUsage) {
	var usage modifierUsage
	path := strconv.Quote(fm.OCSFPath)
	parts := make([]string, 0, len(fm.Values))
	for _, want := range fm.Values {
		w := strconv.Quote(want)
		switch fm.Modifier {
		case ModContains:
			usage.strings = true
			parts = append(parts, fmt.Sprintf("strings.Contains(ev[%s], %s)", path, w))
		case ModStartsWith:
			usage.strings = true
			parts = append(parts, fmt.Sprintf("strings.HasPrefix(ev[%s], %s)", path, w))
		case ModEndsWith:
			usage.strings = true
			parts = append(parts, fmt.Sprintf("strings.HasSuffix(ev[%s], %s)", path, w))
		case ModRegex:
			usage.regexp = true
			parts = append(parts, fmt.Sprintf("regexp.MustCompile(%s).MatchString(ev[%s])", w, path))
		case ModBase64:
			usage.base64 = true
			parts = append(parts, fmt.Sprintf("decodeBase64Eq(ev[%s], %s)", path, w))
		default:
			parts = append(parts, fmt.Sprintf("ev[%s] == %s", path, w))
		}
	}
	joiner := " || "
	if fm.AllOf {
		joiner = " && "
	}
	expr := "(" + strings.Join(parts, joiner) + ")"
	if fm.Modifier == ModBase64 {
		usage.base64 = true
	}
	return expr, usage
}

// emitConditionExpr mirrors interpret.go's evaluateCondition, but emits
// a Go expression string over selVar's generated variable names instead
// of evaluating anything itself.
func emitConditionExpr(expr ConditionExpr, selVar map[string]string, selections map[string]Selection) string {
	switch e := expr.(type) {
	case SelectionRef:
		return selVar[e.Name]
	case OfExpr:
		names := matchSelectionPattern(e.Pattern, selections)
		vars := make([]string, 0, len(names))
		for _, n := range names {
			vars = append(vars, "boolToInt("+selVar[n]+")")
		}
		sum := strings.Join(vars, "+")
		if e.Count < 0 {
			return fmt.Sprintf("(%s) == %d", sum, len(names))
		}
		return fmt.Sprintf("(%s) >= %d", sum, e.Count)
	case NotExpr:
		return "!(" + emitConditionExpr(e.X, selVar, selections) + ")"
	case AndExpr:
		return "(" + emitConditionExpr(e.X, selVar, selections) + " && " + emitConditionExpr(e.Y, selVar, selections) + ")"
	case OrExpr:
		return "(" + emitConditionExpr(e.X, selVar, selections) + " || " + emitConditionExpr(e.Y, selVar, selections) + ")"
	default:
		return "false"
	}
}

// decodeBase64EqSrc emits the base64 modifier's shared helper, only when
// at least one rule actually uses it — mirrors interpret.go's own
// matchOne ModBase64 branch exactly, so the two implementations stay
// provably equivalent rather than independently hand-written twice.
func decodeBase64EqSrc(used bool) string {
	if !used {
		return ""
	}
	return "func decodeBase64Eq(actual, want string) bool {\n" +
		"\tdecoded, err := base64.StdEncoding.DecodeString(want)\n" +
		"\tif err != nil {\n\t\treturn false\n\t}\n" +
		"\treturn actual == string(decoded)\n}\n\n"
}

func ruleFuncName(slug string) string {
	return "ruleMatch_" + sanitizeIdent(slug)
}

// sanitizeIdent turns a rule id or selection name into a valid Go
// identifier fragment — hyphens and dots to underscores, and (Go
// identifiers cannot start with a digit) an underscore prefix if the
// first character would otherwise be one. Deterministic and collision-
// free for this corpus's own UUID-shaped ids.
func sanitizeIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	out := b.String()
	if out == "" || (out[0] >= '0' && out[0] <= '9') {
		out = "_" + out
	}
	return out
}

func goStringSlice(ss []string) string {
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = strconv.Quote(s)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

// goEventLiteral emits a fixture's Event as a Go map literal — used only
// inside generated _test.go files, which is why map[string]string is
// spelled out rather than referencing this package's own Event alias
// (the generated test file does not import sigmac at all).
func goEventLiteral(ev Event) string {
	keys := make([]string, 0, len(ev))
	for k := range ev {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("map[string]string{")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s: %s, ", strconv.Quote(k), strconv.Quote(ev[k]))
	}
	b.WriteString("}")
	return b.String()
}
