// Command sigmac-gen is P2-02's own build step: parse every rule in
// detections/rules (P2-01), require a fixture pair for each
// (detections/fixtures), and write the compiled Go predicates plus their
// generated tests to services/detect/internal/detectgen — committed,
// per ADR-0004. P2-07 extends it with the same "build-time" enforcement
// for MITRE tags: every rule's tag is checked against the pinned ATT&CK
// catalogue (AC1/AC2), and the resulting coverage report / Navigator
// layer are written and committed alongside the compiled rules.
//
// Run via `go generate` or directly:
//
//	go run ./cmd/sigmac-gen
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ajeetsingh272/ai-security-analyst/services/detect/internal/attck"
	"github.com/ajeetsingh272/ai-security-analyst/services/detect/internal/sigmac"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "sigmac-gen:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}
	rulesDir := filepath.Join(root, "detections", "rules")
	fixturesDir := filepath.Join(root, "detections", "fixtures")
	outDir := filepath.Join(root, "services", "detect", "internal", "detectgen")
	docsDir := filepath.Join(root, "docs", "architecture")

	rules, errs := sigmac.ParseCorpus(rulesDir)
	if len(errs) > 0 {
		for _, e := range errs {
			fmt.Fprintln(os.Stderr, e)
		}
		return fmt.Errorf("%d rule(s) failed to parse", len(errs))
	}

	// AC1/AC2: every rule's MITRE tag validated against the pinned
	// ATT&CK catalogue — an unknown, revoked or deprecated id fails the
	// build, the same way a missing tag already does in sigmac.Parse
	// itself.
	attckRules := make([]attck.Rule, len(rules))
	for i, r := range rules {
		attckRules[i] = attckRule{r}
	}
	if attckErrs := attck.ValidateCorpus(attckRules); len(attckErrs) > 0 {
		for _, e := range attckErrs {
			fmt.Fprintln(os.Stderr, e)
		}
		return fmt.Errorf("%d rule(s) failed ATT&CK technique id validation (%s)", len(attckErrs), attck.CatalogueVersion)
	}

	ruleCode, testCode, err := sigmac.GenerateSource(rules, fixturesDir)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "rules.gen.go"), ruleCode, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "rules.gen_test.go"), testCode, 0o644); err != nil {
		return err
	}

	// AC3/AC4: a coverage report (for a human reviewing gaps) and a
	// real Navigator layer file (for the same review, rendered on the
	// actual ATT&CK matrix) — both derived from the same Report so they
	// can never disagree with each other.
	report := attck.BuildCoverage(attckRules)
	if err := writeCoverageReport(filepath.Join(docsDir, "attack-coverage.md"), report); err != nil {
		return err
	}
	layer := attck.BuildNavigatorLayer(report)
	if err := layer.Validate(); err != nil {
		return fmt.Errorf("generated navigator layer failed its own validation: %w", err)
	}
	if err := writeNavigatorLayer(filepath.Join(docsDir, "attack-coverage.navigator.json"), layer); err != nil {
		return err
	}

	fmt.Printf("sigmac-gen: wrote %d compiled rule(s) to %s\n", len(rules), outDir)
	fmt.Printf("sigmac-gen: ATT&CK coverage %d/%d techniques (%s) — see %s\n",
		report.CoveredCount(), len(report.Techniques), attck.CatalogueVersion, docsDir)
	return nil
}

// attckRule bridges sigmac.Rule to attck.Rule — kept here, not in
// either package, since neither sigmac nor attck has any reason to
// depend on the other; sigmac-gen already depends on both.
type attckRule struct{ r *sigmac.Rule }

func (a attckRule) Title() string       { return a.r.Title }
func (a attckRule) MitreTags() []string { return a.r.MitreIDs }

func writeCoverageReport(path string, report attck.Report) error {
	var b strings.Builder
	fmt.Fprintf(&b, "# ATT&CK technique coverage\n\n")
	fmt.Fprintf(&b, "Generated by `go run ./cmd/sigmac-gen` (services/detect) — not hand-edited. ATT&CK catalogue: %s.\n\n", report.CatalogueVersion)
	fmt.Fprintf(&b, "%d of %d current Enterprise techniques covered by at least one rule.\n\n", report.CoveredCount(), len(report.Techniques))

	fmt.Fprintf(&b, "## By tactic\n\n")
	fmt.Fprintf(&b, "| Tactic | Covered | Total |\n|---|---|---|\n")
	for _, tac := range report.Tactics {
		fmt.Fprintf(&b, "| %s | %d | %d |\n", tac.Tactic, tac.Covered, tac.Total)
	}

	fmt.Fprintf(&b, "\n## Covered techniques\n\n")
	fmt.Fprintf(&b, "| Technique | Name | Rules |\n|---|---|---|\n")
	for _, t := range report.Techniques {
		if t.Covered {
			fmt.Fprintf(&b, "| %s | %s | %s |\n", t.ID, t.Name, strings.Join(t.RuleTitles, "; "))
		}
	}

	fmt.Fprintf(&b, "\n## Uncovered techniques\n\n")
	fmt.Fprintf(&b, "<details><summary>%d uncovered techniques</summary>\n\n", len(report.Techniques)-report.CoveredCount())
	fmt.Fprintf(&b, "| Technique | Name | Tactics |\n|---|---|---|\n")
	for _, t := range report.Techniques {
		if !t.Covered {
			fmt.Fprintf(&b, "| %s | %s | %s |\n", t.ID, t.Name, strings.Join(t.Tactics, ", "))
		}
	}
	fmt.Fprintf(&b, "\n</details>\n")

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func writeNavigatorLayer(path string, layer *attck.Layer) error {
	// Sorted so regeneration is diff-free when nothing actually changed
	// (the same property scripts/validate-detections.sh already checks
	// for detectgen's own output).
	sort.Slice(layer.Techniques, func(i, j int) bool { return layer.Techniques[i].TechniqueID < layer.Techniques[j].TechniqueID })
	data, err := json.MarshalIndent(layer, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0o644)
}

// repoRoot walks up from the working directory to the first ancestor
// containing go.work — this binary is run both via `go run
// ./cmd/sigmac-gen` from services/detect and via CI from the repo root,
// so it cannot assume either.
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find go.work above %s", dir)
		}
		dir = parent
	}
}
