// Package sentinelaudit is the Go port of packages/db's audit-log hash
// chain (P0-06 AC1, ADR-0007, TG6) — ported here, once, properly, for
// P3-03, rather than per-service, exactly matching the trigger
// docs/adr/0011-entity-resolution-alias-graph.md itself named ("a
// second Go service needs to write an audited, attributable event...
// port the hash chain to Go once, properly").
//
// entry_hash = SHA256(prev_hash || canonical_json(content)) is only a
// chain if Go and TypeScript ALWAYS produce byte-identical canonical
// JSON for the same logical content — a single writer disagreeing
// with itself across languages would make a real tamper report
// indistinguishable from the two implementations merely drifting
// apart. This file is a deliberate, careful port of
// packages/db/scripts/canonical-json.mjs, verified directly against
// ground-truth hashes generated by running the REAL TypeScript
// implementation (sentinelaudit_test.go's own TestComputeEntryHash_
// MatchesTypeScriptGroundTruth), not inferred from reading the
// algorithm alone.
package sentinelaudit

import (
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
)

// CanonicalJSON ports canonical-json.mjs's own recursive algorithm
// exactly: object keys sorted at every level of nesting (plain string
// comparison — Go's own sort.Strings on UTF-8 bytes agrees with JS's
// default UTF-16-code-unit string sort for every key this codebase
// actually uses), arrays left in their given order, no whitespace
// anywhere.
//
// Deliberately NOT built on encoding/json.Marshal: Go's own Marshal
// HTML-escapes '<', '>', '&' by default (producing < etc.), which
// JS's JSON.stringify does not do at all — a silent, byte-level
// mismatch that would make this port's hashes diverge from
// TypeScript's for any payload containing those characters. Every
// string is escaped by hand instead, matching JSON.stringify's own
// escaping rules precisely (writeJSONString below).
//
// Accepts only the types Go code in this repo actually constructs for
// an audit payload — string, bool, nil, int, int64, float64, []any,
// map[string]any — and returns an error for anything else, rather
// than silently producing a hash that does not mean what it claims to.
func CanonicalJSON(value any) (string, error) {
	var sb strings.Builder
	if err := writeCanonical(&sb, value); err != nil {
		return "", err
	}
	return sb.String(), nil
}

func writeCanonical(sb *strings.Builder, value any) error {
	switch v := value.(type) {
	case nil:
		sb.WriteString("null")
	case bool:
		if v {
			sb.WriteString("true")
		} else {
			sb.WriteString("false")
		}
	case string:
		writeJSONString(sb, v)
	case int:
		sb.WriteString(strconv.Itoa(v))
	case int64:
		sb.WriteString(strconv.FormatInt(v, 10))
	case float64:
		writeJSONNumber(sb, v)
	case []any:
		sb.WriteByte('[')
		for i, item := range v {
			if i > 0 {
				sb.WriteByte(',')
			}
			if err := writeCanonical(sb, item); err != nil {
				return err
			}
		}
		sb.WriteByte(']')
	case map[string]any:
		keys := make([]string, 0, len(v))
		for k := range v {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		sb.WriteByte('{')
		for i, k := range keys {
			if i > 0 {
				sb.WriteByte(',')
			}
			writeJSONString(sb, k)
			sb.WriteByte(':')
			if err := writeCanonical(sb, v[k]); err != nil {
				return err
			}
		}
		sb.WriteByte('}')
	default:
		return fmt.Errorf("sentinelaudit: unsupported type %T for canonical JSON", value)
	}
	return nil
}

// writeJSONString matches JSON.stringify's own escaping exactly:
// quote, backslash, and the control characters JS gives short escapes
// to; every other control character as \u00XX; everything else
// (including unicode, '<', '>', '&') written through unescaped — JS's
// JSON.stringify does not escape those, so this must not either.
func writeJSONString(sb *strings.Builder, s string) {
	sb.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			sb.WriteString(`\"`)
		case '\\':
			sb.WriteString(`\\`)
		case '\n':
			sb.WriteString(`\n`)
		case '\r':
			sb.WriteString(`\r`)
		case '\t':
			sb.WriteString(`\t`)
		case '\b':
			sb.WriteString(`\b`)
		case '\f':
			sb.WriteString(`\f`)
		default:
			if r < 0x20 {
				fmt.Fprintf(sb, `\u%04x`, r)
			} else {
				sb.WriteRune(r)
			}
		}
	}
	sb.WriteByte('"')
}

// writeJSONNumber matches JS's Number.toString() for the case that
// actually matters here: every Go float64 arriving through this
// package represents a JSON number that was almost always typed as a
// plain integer by the calling code (a count, an index, a schema
// version) — JS prints "3", never "3.0", for a whole number, so a
// whole-valued float64 is formatted without a decimal point to match.
// Genuinely fractional values fall back to Go's own shortest
// round-trippable representation, which agrees with JS's algorithm
// for every ordinary decimal value audit payloads in this codebase
// actually contain.
func writeJSONNumber(sb *strings.Builder, f float64) {
	if !math.IsInf(f, 0) && !math.IsNaN(f) && f == math.Trunc(f) && math.Abs(f) < 1e15 {
		sb.WriteString(strconv.FormatInt(int64(f), 10))
		return
	}
	sb.WriteString(strconv.FormatFloat(f, 'g', -1, 64))
}
