package sentinelaudit

import (
	"encoding/hex"
	"testing"
)

// TestComputeEntryHash_MatchesTypeScriptGroundTruth is this port's own
// reason for existing: three hashes generated by actually RUNNING
// packages/db/scripts/chain-verifier.mjs (the real TypeScript
// implementation, via node) against these exact literal inputs — not
// inferred from reading the algorithm, computed for real and pasted
// here. If this test ever fails, the two languages' chains have
// silently diverged and NO audit entry written by one can be verified
// by the other from that point on — this is the single most important
// test in this package.
func TestComputeEntryHash_MatchesTypeScriptGroundTruth(t *testing.T) {
	// entry1: GENESIS_HASH as prev, a plain integer payload.
	content1 := AuditEntryContent{
		TenantID: "11111111-1111-4111-8111-111111111111", OccurredAt: "2026-01-01T00:00:00.000Z",
		ActorType: "system", ActorID: "test-writer", Action: "action-0",
		SubjectType: "test", SubjectID: "subject-0",
		Payload: map[string]any{"index": float64(0), "note": "entry 0"},
	}
	hash1, err := ComputeEntryHash(GenesisHash, content1)
	if err != nil {
		t.Fatalf("ComputeEntryHash (entry1): %v", err)
	}
	wantHash1 := mustDecodeHex(t, "aec2cce4f99215878b7aa8ff599dcdcfa66b2df59ae9b142b968a80753586c5f")
	if hex.EncodeToString(hash1) != hex.EncodeToString(wantHash1) {
		t.Fatalf("entry1 hash mismatch\n got:  %x\n want: %x", hash1, wantHash1)
	}

	// entry2: chained off entry1's own hash, with nested objects and
	// an array — proving key-sort-at-every-level and array-order-
	// preserved both match the TypeScript implementation.
	content2 := AuditEntryContent{
		TenantID: "11111111-1111-4111-8111-111111111111", OccurredAt: "2026-01-01T00:00:01.000Z",
		ActorType: "system", ActorID: "test-writer", Action: "action-1",
		SubjectType: "test", SubjectID: "subject-1",
		Payload: map[string]any{
			"index": float64(1), "note": "entry 1",
			"nested": map[string]any{"z": float64(1), "a": float64(2)},
			"arr":    []any{float64(3), float64(1), float64(2)},
		},
	}
	hash2, err := ComputeEntryHash(hash1, content2)
	if err != nil {
		t.Fatalf("ComputeEntryHash (entry2): %v", err)
	}
	wantHash2 := mustDecodeHex(t, "d155e69dc126f8aee6e96ee45882ddfc418c7fca1250c7583c0d5fa26dd000ad")
	if hex.EncodeToString(hash2) != hex.EncodeToString(wantHash2) {
		t.Fatalf("entry2 hash mismatch\n got:  %x\n want: %x", hash2, wantHash2)
	}

	// entry3: string-escaping edge cases — quotes, backslashes,
	// control characters, unicode, null, bool, a fractional number —
	// everything writeJSONString/writeJSONNumber specifically exist
	// to get byte-identical to JSON.stringify.
	content3 := AuditEntryContent{
		TenantID: "22222222-2222-4222-8222-222222222222", OccurredAt: "2026-01-01T00:00:02.000Z",
		ActorType: "human", ActorID: "user-éè", Action: `quote"and\backslash`,
		SubjectType: "test", SubjectID: "subject/with/slashes",
		Payload: map[string]any{
			"text": "line1\nline2\ttab", "unicode": " é", "empty": nil, "bool": true, "num": 3.14159,
		},
	}
	hash3, err := ComputeEntryHash(GenesisHash, content3)
	if err != nil {
		t.Fatalf("ComputeEntryHash (entry3): %v", err)
	}
	wantHash3 := mustDecodeHex(t, "e9e2d3ee238bc1c3d8322a6b2b1af14a362459863ff453b68d3edcf9719614e2")
	if hex.EncodeToString(hash3) != hex.EncodeToString(wantHash3) {
		t.Fatalf("entry3 hash mismatch\n got:  %x\n want: %x", hash3, wantHash3)
	}
}

func mustDecodeHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("decoding ground-truth hex %q: %v", s, err)
	}
	return b
}

func TestGenesisHash_Is32ZeroBytes(t *testing.T) {
	if len(GenesisHash) != 32 {
		t.Fatalf("len(GenesisHash) = %d, want 32", len(GenesisHash))
	}
	for i, b := range GenesisHash {
		if b != 0 {
			t.Fatalf("GenesisHash[%d] = %d, want 0", i, b)
		}
	}
}

func TestComputeEntryHash_DifferentPrevHashProducesDifferentHash(t *testing.T) {
	content := AuditEntryContent{TenantID: "t", OccurredAt: "o", ActorType: "system", ActorID: "a", Action: "x", SubjectType: "s", SubjectID: "i", Payload: map[string]any{}}
	h1, err := ComputeEntryHash(GenesisHash, content)
	if err != nil {
		t.Fatalf("ComputeEntryHash: %v", err)
	}
	otherPrev := make([]byte, 32)
	otherPrev[0] = 1
	h2, err := ComputeEntryHash(otherPrev, content)
	if err != nil {
		t.Fatalf("ComputeEntryHash: %v", err)
	}
	if hex.EncodeToString(h1) == hex.EncodeToString(h2) {
		t.Fatal("different prevHash values produced the SAME entry hash")
	}
}
