/**
 * P6-03 (TG1: "AI output is never unsourced"): the case detail screen's
 * own backend — the plain-English verdict, the full history, the MITRE
 * explanation for each signal, the recommended actions with an approval
 * control, and the evidence-resolution endpoint every expandable claim
 * calls to prove itself against the real event store.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import type { FastifyInstance } from 'fastify';
import fp from 'fastify-plugin';
import type { Pool } from 'pg';
import type { ClickHouseClient } from '@clickhouse/client';
import { CasesRepository, ActionsRepository, InvestigationTranscriptRepository, AuditLogWriter, withTenantContext } from '@sentinel/db';
import type { Verdict } from '@sentinel/schema';
import { requireRole } from '../auth/rbac.js';
import { requiresStepUp, verifyStepUpPassword } from '../approvals/step-up.js';
import { executeApprovedAction } from '../approvals/execute-action.js';
import { queryAsTenant } from '../clickhouse.js';

export interface CaseDetailRoutesOptions {
  pool: Pool;
  /** Undefined when CLICKHOUSE_URL is unset — the evidence route
   * answers 503, not a crash, same pattern as every other optional
   * integration in app.ts. */
  clickhouse: ClickHouseClient | undefined;
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));

interface MitreGlossaryEntry {
  id: string;
  name: string;
  description: string;
  ruleTitles: string[];
}

// Read once at startup, not per-request — this file is regenerated by
// `pnpm --filter @sentinel/api build:mitre-glossary` (committed, not
// built at deploy time), the same "generated asset checked into the
// repo" convention @sentinel/design-tokens' own CSS output already uses.
const MITRE_GLOSSARY: MitreGlossaryEntry[] = JSON.parse(
  readFileSync(path.join(__dirname, '..', 'mitre-glossary.generated.json'), 'utf8'),
);
const MITRE_BY_ID = new Map(MITRE_GLOSSARY.map((e) => [e.id, e]));

/** A rule's own tag can be a sub-technique id ("T1098.002") or a bare
 * parent ("T1098") — case_signals.mitre_ids stores whatever the
 * matching rule declared, so both forms must resolve. */
function lookupMitre(id: string): MitreGlossaryEntry | null {
  return MITRE_BY_ID.get(id.toUpperCase()) ?? null;
}

/** Loose, read-side shape guard — NOT a re-implementation of
 * apps/analyst's own validateVerdict (P4-03), which already ran once at
 * write time and is that app's own concern. This only protects the
 * dashboard from rendering a half-formed object if an older or
 * differently-shaped row ever turns up, by requiring the handful of
 * fields this screen actually reads to be present. */
function asVerdict(value: unknown): Verdict | null {
  if (typeof value !== 'object' || value === null) return null;
  const v = value as Record<string, unknown>;
  if (typeof v.severity !== 'string' || typeof v.title !== 'string' || !Array.isArray(v.claims) || !Array.isArray(v.recommendedActions)) {
    return null;
  }
  return v as unknown as Verdict;
}

interface EventRow {
  event_id: string;
  time: string;
  class_uid: number;
  category_uid: number;
  activity_id: number;
  severity_id: number;
  actor_user_uid: string | null;
  target_uid: string | null;
  src_ip: string | null;
  message: string | null;
}

// T2's own scenario: a claim's evidenceRef can legitimately reference an
// event that exists but has not reached ClickHouse yet (P1-11's own
// ingest-lag metric is real — see packages/observability's own
// integration test — this is the one place that lag is visible to a
// human, not just to a Prometheus alert). There is no per-event
// "indexed yet?" flag anywhere in this schema to check directly, so this
// is a heuristic, disclosed as one: an unresolved id for a case created
// more recently than this window is "still indexing," not "missing."
const PENDING_WINDOW_MS = 5 * 60 * 1000;

async function caseDetailRoutesImpl(fastify: FastifyInstance, options: CaseDetailRoutesOptions): Promise<void> {
  const { pool, clickhouse } = options;

  fastify.get('/cases/:id', { preHandler: requireRole('read_only') }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const tenantId = request.session!.tenantId;

    const result = await withTenantContext(tenantId, async () => {
      const cases = new CasesRepository(pool);
      const history = await cases.history(id, 50);
      if (!history.case) return null;

      const transcripts = await new InvestigationTranscriptRepository(pool).listForCase(id);
      const verdict = asVerdict(transcripts[0]?.verdict ?? null);

      const actions = await new ActionsRepository(pool).listForCase(id);

      const mitre = [...new Set(history.signals.flatMap((s) => s.mitreIds))]
        .map(lookupMitre)
        .filter((e): e is MitreGlossaryEntry => e !== null);

      return { case: history.case, signals: history.signals, transitions: history.transitions, verdict, actions, mitre };
    });

    if (!result) return reply.code(404).send({ error: 'not_found' });
    return reply.code(200).send(result);
  });

  // AC2/T1/T2: every claim's own "show me the evidence" control calls
  // this with the exact ids its own evidenceRef array names.
  fastify.get('/cases/:id/evidence', { preHandler: requireRole('read_only') }, async (request, reply) => {
    if (!clickhouse) return reply.code(503).send({ error: 'clickhouse_unconfigured' });
    const { id: caseId } = request.params as { id: string };
    const tenantId = request.session!.tenantId;
    const query = request.query as { ids?: string };
    const requestedIds = (query.ids ?? '').split(',').filter((s) => s.length > 0);
    if (requestedIds.length === 0) return reply.code(400).send({ error: 'ids_required' });

    const caseRow = await withTenantContext(tenantId, () => new CasesRepository(pool).findById(caseId));
    if (!caseRow) return reply.code(404).send({ error: 'not_found' });

    const rows = await queryAsTenant<EventRow>(clickhouse, {
      tenantId,
      query: `
        SELECT event_id, time, class_uid, category_uid, activity_id, severity_id,
               actor_user_uid, target_uid, src_ip, message
        FROM sentinel.events
        WHERE tenant_id = {tenantId:UUID} AND event_id IN {ids:Array(String)}`,
      query_params: { tenantId, ids: requestedIds },
    });
    const byId = new Map(rows.map((r) => [r.event_id, r]));

    const isRecent = Date.now() - new Date(caseRow.createdAt).getTime() < PENDING_WINDOW_MS;
    const results = requestedIds.map((requestedId) => {
      const event = byId.get(requestedId);
      if (event) return { id: requestedId, status: 'found' as const, event };
      return { id: requestedId, status: (isRecent ? 'pending' : 'not_found') as 'pending' | 'not_found' };
    });

    return reply.code(200).send({ results });
  });

  // AC4's own approval control. Session-authenticated — the signed-token
  // flow (apps/api/src/routes/approvals.ts) exists for WhatsApp/Slack/
  // email links delivered to someone who may not be looking at the
  // dashboard at all; a user already looking at THIS screen, already
  // signed in, approves through their own session instead. Step-up
  // (P5-04) is enforced identically either way — requiresStepUp/
  // verifyStepUpPassword take only a pool and a user id, no token
  // coupling at all, so this reuses them directly rather than a second
  // implementation of the same rule.
  fastify.post('/cases/:caseId/actions/:actionId/approve', { preHandler: requireRole('analyst') }, async (request, reply) => {
    const { caseId, actionId } = request.params as { caseId: string; actionId: string };
    const session = request.session!;
    const body = request.body as { stepUpPassword?: string } | undefined;

    const outcome = await withTenantContext(session.tenantId, async () => {
      const actions = new ActionsRepository(pool);
      const action = await actions.findById(actionId);
      if (!action || action.caseId !== caseId) return { kind: 'not_found' as const };

      if (requiresStepUp(action.playbook)) {
        const stepUpOk = body?.stepUpPassword ? await verifyStepUpPassword(pool, session.userId, body.stepUpPassword) : false;
        if (!stepUpOk) {
          await new AuditLogWriter(pool).insert({
            actorType: 'human',
            actorId: session.userId,
            action: 'step_up_failed',
            subjectType: 'action',
            subjectId: actionId,
            payload: { playbook: action.playbook, via: 'dashboard' },
          });
          return { kind: 'step_up_failed' as const };
        }
      }

      const approved = await actions.approve(actionId, caseId, session.userId, requiresStepUp(action.playbook) ? true : undefined);
      if (!approved) return { kind: 'decided' as const, approved: false };

      await executeApprovedAction(pool, session.tenantId, action);
      return { kind: 'decided' as const, approved: true };
    });

    if (outcome.kind === 'not_found') return reply.code(404).send({ error: 'not_found' });
    if (outcome.kind === 'step_up_failed') return reply.code(401).send({ error: 'step_up_failed' });
    return reply.code(200).send({ ok: true, approved: outcome.approved });
  });
}

export const caseDetailRoutes = fp(caseDetailRoutesImpl, { name: 'sentinel-case-detail' });
