// Code generated by sigmac-gen from detections/rules and detections/fixtures. DO NOT EDIT.

package detectgen

import (
	"strings"
)

type CompiledRule struct {
	ID               string
	Title            string
	Level            string
	MitreIDs         []string
	Engine           string
	OwnerDescription string
	Matches          func(ev map[string]string) bool
}

var Rules = []CompiledRule{
	{ID: "8f1a2b3c-0001-4a00-9000-000000000015", Title: "Tenant-wide admin consent granted to an application", Level: "critical", MitreIDs: []string{"attack.t1098.003"}, Engine: "in-stream", OwnerDescription: "An administrator approved an outside app's access for everyone in the company at once, rather than just for themselves. If this was not planned, it is worth checking what that app can now see or do.\n", Matches: ruleMatch_admin_consent_granted_to_application},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000005", Title: "Sign-in through a known anonymiser or proxy", Level: "high", MitreIDs: []string{"attack.t1090.003"}, Engine: "in-stream", OwnerDescription: "Someone signed in to this account through a service that hides where they are really connecting from. Attackers commonly use this trick to hide their real location when they are using a stolen password.\n", Matches: ruleMatch_anonymous_proxy_signin},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000036", Title: "New application registration created", Level: "low", MitreIDs: []string{"attack.t1098.001"}, Engine: "in-stream", OwnerDescription: "A new app was registered with the company's Microsoft 365 account. This is a normal step for connecting new business tools, but it is also the first step someone would take before giving an app broad access to company data.\n", Matches: ruleMatch_application_registration_created},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000013", Title: "Conditional access policy disabled", Level: "high", MitreIDs: []string{"attack.t1685"}, Engine: "in-stream", OwnerDescription: "A sign-in security rule for the company was turned off. These rules usually block risky sign-ins, so turning one off can open a door for an attacker.\n", Matches: ruleMatch_conditional_access_policy_disabled},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000018", Title: "New device registered to Azure AD", Level: "low", MitreIDs: []string{"attack.t1098.005"}, Engine: "in-stream", OwnerDescription: "A new device was registered to the company's Microsoft 365 account. Attackers sometimes register their own device so it is trusted, which lets them keep signing in without extra checks.\n", Matches: ruleMatch_device_registration_unusual},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000025", Title: "Data loss prevention policy disabled", Level: "high", MitreIDs: []string{"attack.t1685"}, Engine: "in-stream", OwnerDescription: "A rule that normally blocks sensitive company information, like customer data, from leaving the company was turned off. Someone may do this right before trying to send data outside the company.\n", Matches: ruleMatch_dlp_policy_disabled},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000034", Title: "Domain federation settings changed", Level: "critical", MitreIDs: []string{"attack.t1484.002"}, Engine: "in-stream", OwnerDescription: "The company changed how one of its email domains proves who its users are when they sign in. This is a sensitive, rarely-changed setting — someone who changes it without permission could make Microsoft trust sign-ins they control.\n", Matches: ruleMatch_domain_federation_settings_changed},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000021", Title: "eDiscovery content search created", Level: "medium", MitreIDs: []string{"attack.t1213"}, Engine: "in-stream", OwnerDescription: "A company-wide search was created that can look through many people's mailboxes and files at once. This tool is normally used by legal or compliance teams, but someone with admin access could misuse it to find sensitive information.\n", Matches: ruleMatch_ediscovery_search_created},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000017", Title: "Guest account added to a privileged directory role", Level: "high", MitreIDs: []string{"attack.t1136.003"}, Engine: "in-stream", OwnerDescription: "An outside guest account, not one of the company's own employees, was given admin-level access. This is unusual and worth checking, since guest accounts are not normally given this level of control.\n", Matches: ruleMatch_guest_user_granted_directory_role},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000033", Title: "High-privilege permission granted to a user-assigned application", Level: "medium", MitreIDs: []string{"attack.t1098.003"}, Engine: "in-stream", OwnerDescription: "A person was given a powerful level of access through a connected app, rather than directly. This is a less obvious way to grant broad access, so it is worth checking if it was intended.\n", Matches: ruleMatch_high_privilege_app_permission_granted},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000008", Title: "Impossible travel between sign-ins", Level: "high", MitreIDs: []string{"attack.t1078.004"}, Engine: "windowed", OwnerDescription: "The same person signed in from two different places in a short amount of time — faster than someone could realistically travel between them. This usually means someone besides the real owner has their password.\n", Matches: ruleMatch_impossible_travel},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000012", Title: "Inbox rule created to hide incoming messages", Level: "medium", MitreIDs: []string{"attack.t1564.008"}, Engine: "in-stream", OwnerDescription: "A rule was created on this mailbox that automatically marks certain incoming emails as already read. Attackers use this to hide warning emails, like security alerts, from the real owner of the account.\n", Matches: ruleMatch_inbox_rule_hides_messages},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000010", Title: "Sign-in using a legacy authentication protocol", Level: "medium", MitreIDs: []string{"attack.t1078.004"}, Engine: "in-stream", OwnerDescription: "Someone signed in using an older connection method that cannot be protected by extra security steps like a second approval code. Attackers often use this method on purpose because it can slip past modern account protections.\n", Matches: ruleMatch_legacy_auth_signin},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000035", Title: "Inbound or outbound mail connector added", Level: "medium", MitreIDs: []string{"attack.t1114"}, Engine: "in-stream", OwnerDescription: "A new route was set up for how email flows into the company. A connector added without IT's knowledge could be used to secretly redirect or copy company email.\n", Matches: ruleMatch_mail_flow_connector_added},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000031", Title: "Mailbox audit bypass enabled for an account", Level: "high", MitreIDs: []string{"attack.t1685.002"}, Engine: "in-stream", OwnerDescription: "A specific account or app was excused from having its mailbox activity recorded. This is sometimes used for trusted internal tools, but it can also let someone's actions go unrecorded on purpose.\n", Matches: ruleMatch_mailbox_audit_bypass_enabled},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000011", Title: "Mailbox audit logging disabled", Level: "high", MitreIDs: []string{"attack.t1685.002"}, Engine: "in-stream", OwnerDescription: "Someone turned off the activity record-keeping for a mailbox. Attackers do this so their actions inside an account cannot be reviewed later.\n", Matches: ruleMatch_mailbox_audit_disabled},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000023", Title: "Full access permission granted on another mailbox", Level: "medium", MitreIDs: []string{"attack.t1098.002"}, Engine: "in-stream", OwnerDescription: "One person was given permission to fully open and read someone else's mailbox. This is sometimes needed for a real business reason, like covering for an assistant, but it should match something the company actually asked for.\n", Matches: ruleMatch_mailbox_delegate_permission_added},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000020", Title: "Mailbox content exported to a local file", Level: "medium", MitreIDs: []string{"attack.t1114"}, Engine: "in-stream", OwnerDescription: "The full contents of a mailbox were exported to a file that can be saved or copied elsewhere. IT sometimes does this during investigations, but it is also how someone could copy out an entire mailbox at once.\n", Matches: ruleMatch_mailbox_export_to_pst},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000007", Title: "Mass file download or deletion within a short window", Level: "high", MitreIDs: []string{"attack.t1530"}, Engine: "windowed", OwnerDescription: "One person downloaded or deleted an unusually large number of files in a short time. This can happen when an account has been taken over and someone is copying or destroying company files.\n", Matches: ruleMatch_mass_file_download},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000006", Title: "Mass mailbox item access within a short window", Level: "high", MitreIDs: []string{"attack.t1114.002"}, Engine: "windowed", OwnerDescription: "An unusually large number of emails were opened or copied from one mailbox in a short time. This can happen when someone has broken into the account and is copying out its contents.\n", Matches: ruleMatch_mass_mailbox_download},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000019", Title: "Repeated MFA prompt failures for one account", Level: "high", MitreIDs: []string{"attack.t1621"}, Engine: "windowed", OwnerDescription: "One account received an unusual number of sign-in approval requests in a short time that were all turned down. Attackers sometimes send a flood of these requests, hoping the real owner will approve one by accident.\n", Matches: ruleMatch_mfa_fatigue_push_bombing},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000004", Title: "MFA method registration outside business hours", Level: "medium", MitreIDs: []string{"attack.t1556.006"}, Engine: "in-stream", OwnerDescription: "Someone added a new way to prove their identity on this account (like a new phone number or app) outside of normal office hours. Attackers often do this right after stealing a password, so they can get back in even if the real owner changes it.\n", Matches: ruleMatch_mfa_method_registration},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000016", Title: "Multi-factor authentication disabled for a user", Level: "critical", MitreIDs: []string{"attack.t1556.006"}, Engine: "in-stream", OwnerDescription: "The extra sign-in approval step, beyond just a password, was turned off for an account. Attackers do this to make it easier to keep using a stolen password without that second check getting in the way.\n", Matches: ruleMatch_mfa_requirement_removed},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000032", Title: "New mobile device linked to a mailbox", Level: "low", MitreIDs: []string{"attack.t1098.005"}, Engine: "in-stream", OwnerDescription: "A new phone or tablet was connected to someone's email account. This happens whenever someone sets up email on a new device, but it is also how someone could keep reading another person's email after stealing their password.\n", Matches: ruleMatch_mobile_device_added_to_mailbox},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000001", Title: "New inbox forwarding rule to an external address", Level: "medium", MitreIDs: []string{"attack.t1114.003"}, Engine: "in-stream", OwnerDescription: "A rule was set up on this mailbox that automatically sends a copy of incoming email to an outside address, often without the owner knowing. This is a common way attackers quietly read someone's email after breaking into their account.\n", Matches: ruleMatch_new_inbox_forwarding_rule},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000024", Title: "High-privilege permission granted to an application", Level: "high", MitreIDs: []string{"attack.t1528"}, Engine: "in-stream", OwnerDescription: "A connected app was given a powerful level of access to company data. If IT did not set this up on purpose, it is worth checking exactly what that app can now see or change.\n", Matches: ruleMatch_oauth_app_high_privilege_scope_granted},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000002", Title: "OAuth consent grant to an unverified application", Level: "high", MitreIDs: []string{"attack.t1528"}, Engine: "in-stream", OwnerDescription: "Someone gave an outside app permission to access this Microsoft 365 account, and Microsoft has not reviewed or approved that app. This is a common trick attackers use to keep access to an account without needing the password again.\n", Matches: ruleMatch_oauth_consent_unverified_app},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000038", Title: "Account password set to never expire", Level: "medium", MitreIDs: []string{"attack.t1098"}, Engine: "in-stream", OwnerDescription: "An account was set up so its password never has to be changed. This removes a normal safety net — if that password were ever stolen, it would keep working indefinitely.\n", Matches: ruleMatch_password_never_expires_set},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000009", Title: "Password spray against multiple accounts from one source", Level: "high", MitreIDs: []string{"attack.t1110.003"}, Engine: "windowed", OwnerDescription: "One computer tried signing in to several different accounts and failed, all within a few minutes. This is a common way attackers try to guess passwords across many accounts at once, instead of guessing many passwords against just one account.\n", Matches: ruleMatch_password_spray},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000003", Title: "Privileged directory role assignment", Level: "medium", MitreIDs: []string{"attack.t1098.003"}, Engine: "in-stream", OwnerDescription: "Someone was given admin-level access to the company's Microsoft 365 setup. This is normal when IT does it on purpose, but worth a second look if it was not expected.\n", Matches: ruleMatch_privileged_role_assignment},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000039", Title: "Remote PowerShell access enabled for a mailbox user", Level: "medium", MitreIDs: []string{"attack.t1078.004"}, Engine: "in-stream", OwnerDescription: "An account was given the ability to manage Microsoft 365 through scripted commands instead of the normal web page. This is a powerful capability usually reserved for IT administrators.\n", Matches: ruleMatch_remote_powershell_enabled_for_user},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000037", Title: "Member added to a privileged group", Level: "low", MitreIDs: []string{"attack.t1098.003"}, Engine: "in-stream", OwnerDescription: "Someone was added to a company group. Some groups automatically carry admin-level access, so a new member in one of those groups deserves the same attention as being made an admin directly.\n", Matches: ruleMatch_role_assignable_group_membership_changed},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000040", Title: "Safe attachments protection disabled", Level: "high", MitreIDs: []string{"attack.t1685"}, Engine: "in-stream", OwnerDescription: "A protection that automatically checks email attachments for harmful content was turned off. Someone may disable this right before sending a harmful file by email.\n", Matches: ruleMatch_safe_attachments_policy_disabled},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000014", Title: "Credential added to an application's service principal", Level: "high", MitreIDs: []string{"attack.t1098.001"}, Engine: "in-stream", OwnerDescription: "A new password or security certificate was added to one of the company's connected apps. If IT did not do this, it may let someone sign in as that app without ever needing a person's password.\n", Matches: ruleMatch_service_principal_credential_added},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000027", Title: "Anonymous sharing link created for a file", Level: "medium", MitreIDs: []string{"attack.t1567.002"}, Engine: "in-stream", OwnerDescription: "A link was created that lets anyone who has it open a company file, without needing to sign in. This is convenient for sharing, but it means the file is no longer limited to people inside the company.\n", Matches: ruleMatch_sharepoint_anonymous_link_created},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000028", Title: "External guest granted access to a SharePoint site", Level: "medium", MitreIDs: []string{"attack.t1098.003"}, Engine: "in-stream", OwnerDescription: "Someone outside the company was given access to a company site or folder. This is normal for working with partners, but worth checking if it was not expected.\n", Matches: ruleMatch_sharepoint_external_user_granted_access},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000030", Title: "Site collection administrator added", Level: "medium", MitreIDs: []string{"attack.t1098.003"}, Engine: "in-stream", OwnerDescription: "Someone was given full control over a company site, including every file and folder in it. This should match something IT actually did on purpose.\n", Matches: ruleMatch_sharepoint_site_collection_admin_added},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000029", Title: "SharePoint site permission level changed", Level: "low", MitreIDs: []string{"attack.t1098"}, Engine: "in-stream", OwnerDescription: "The access rules for a company site or folder were changed. This is routine site administration most of the time, but is also how someone could open up an area that was supposed to stay restricted.\n", Matches: ruleMatch_sharepoint_site_permission_broadened},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000041", Title: "Tenant-wide unified audit logging disabled", Level: "critical", MitreIDs: []string{"attack.t1685.002"}, Engine: "in-stream", OwnerDescription: "Someone turned off the company-wide activity record-keeping for the whole organization. Attackers do this so none of their actions anywhere in the company's account can be reviewed later.\n", Matches: ruleMatch_tenant_audit_log_disabled},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000022", Title: "Mail flow rule created to forward mail externally", Level: "high", MitreIDs: []string{"attack.t1114.003"}, Engine: "in-stream", OwnerDescription: "A company-wide mail rule was created that can redirect or copy email. Unlike a personal inbox rule, this can affect everyone's email at once, so it deserves a closer look if nobody meant to set it up.\n", Matches: ruleMatch_transport_rule_forwards_externally},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000026", Title: "Trusted network location added to sign-in policy", Level: "medium", MitreIDs: []string{"attack.t1484.002"}, Engine: "in-stream", OwnerDescription: "A network location was added to the list the company treats as safe for signing in. If someone adds their own location to this list without permission, it can let them get around checks meant to catch risky sign-ins.\n", Matches: ruleMatch_trusted_location_added_to_conditional_access},
}

func boolToInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

func ruleMatch_admin_consent_granted_to_application(ev map[string]string) bool {
	sel_selection := (ev["unmapped.ConsentType"] == "AdminConsent") &&
		(ev["metadata.operation"] == "Consent to application.")
	return sel_selection

}

func ruleMatch_anonymous_proxy_signin(ev map[string]string) bool {
	sel_selection := (ev["metadata.is_anonymous_proxy"] == "true") &&
		(ev["metadata.operation"] == "UserLoggedIn") &&
		(ev["unmapped.ResultStatus"] == "Success")
	return sel_selection

}

func ruleMatch_application_registration_created(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Add application.")
	return sel_selection

}

func ruleMatch_conditional_access_policy_disabled(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Update Conditional Access Policy") &&
		(ev["unmapped.PolicyState"] == "Disabled")
	return sel_selection

}

func ruleMatch_device_registration_unusual(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Add device.")
	return sel_selection

}

func ruleMatch_dlp_policy_disabled(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Update policy.") &&
		(ev["unmapped.PolicyState"] == "Disabled")
	return sel_selection

}

func ruleMatch_domain_federation_settings_changed(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Set federation settings on domain.")
	return sel_selection

}

func ruleMatch_ediscovery_search_created(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "New-ComplianceSearch")
	return sel_selection

}

func ruleMatch_guest_user_granted_directory_role(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Add member to role.") &&
		(ev["unmapped.UserType"] == "Guest")
	return sel_selection

}

func ruleMatch_high_privilege_app_permission_granted(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Add app role assignment grant to user.")
	return sel_selection

}

func ruleMatch_impossible_travel(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "UserLoggedIn") &&
		(ev["unmapped.ResultStatus"] == "Success")
	return sel_selection

}

func ruleMatch_inbox_rule_hides_messages(ev map[string]string) bool {
	sel_selection := (ev["unmapped.MarkAsRead"] == "True") &&
		(ev["metadata.operation"] == "New-InboxRule")
	return sel_selection

}

func ruleMatch_legacy_auth_signin(ev map[string]string) bool {
	sel_selection := (ev["unmapped.ClientAppUsed"] == "Other clients") &&
		(ev["metadata.operation"] == "UserLoggedIn")
	return sel_selection

}

func ruleMatch_mail_flow_connector_added(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "New-InboundConnector")
	return sel_selection

}

func ruleMatch_mailbox_audit_bypass_enabled(ev map[string]string) bool {
	sel_selection := (ev["unmapped.AuditBypassEnabled"] == "True") &&
		(ev["metadata.operation"] == "Set-MailboxAuditBypassAssociation")
	return sel_selection

}

func ruleMatch_mailbox_audit_disabled(ev map[string]string) bool {
	sel_selection := (ev["unmapped.AuditEnabled"] == "False") &&
		(ev["metadata.operation"] == "Set-Mailbox")
	return sel_selection

}

func ruleMatch_mailbox_delegate_permission_added(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Add-MailboxPermission")
	return sel_selection

}

func ruleMatch_mailbox_export_to_pst(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "New-MailboxExportRequest")
	return sel_selection

}

func ruleMatch_mass_file_download(ev map[string]string) bool {
	sel_selection1 := (ev["metadata.operation"] == "FileDownloaded")
	sel_selection2 := (ev["metadata.operation"] == "FileDeleted")
	return (sel_selection1 || sel_selection2)

}

func ruleMatch_mass_mailbox_download(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "MailItemsAccessed")
	return sel_selection

}

func ruleMatch_mfa_fatigue_push_bombing(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "UserLoginFailed") &&
		(ev["unmapped.ResultStatus"] == "MfaDenied")
	return sel_selection

}

func ruleMatch_mfa_method_registration(ev map[string]string) bool {
	sel_selection := (strings.HasPrefix(ev["metadata.operation"], "Register security info"))
	return sel_selection

}

func ruleMatch_mfa_requirement_removed(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Disable Strong Authentication.")
	return sel_selection

}

func ruleMatch_mobile_device_added_to_mailbox(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "New-MobileDeviceAssociation")
	return sel_selection

}

func ruleMatch_new_inbox_forwarding_rule(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "New-InboxRule")
	return sel_selection

}

func ruleMatch_oauth_app_high_privilege_scope_granted(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Add app role assignment to service principal.")
	return sel_selection

}

func ruleMatch_oauth_consent_unverified_app(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Consent to application.")
	return sel_selection

}

func ruleMatch_password_never_expires_set(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Set-User") &&
		(ev["unmapped.PasswordNeverExpires"] == "True")
	return sel_selection

}

func ruleMatch_password_spray(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "UserLoginFailed")
	return sel_selection

}

func ruleMatch_privileged_role_assignment(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Add member to role.")
	return sel_selection

}

func ruleMatch_remote_powershell_enabled_for_user(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Set-User") &&
		(ev["unmapped.RemotePowerShellEnabled"] == "True")
	return sel_selection

}

func ruleMatch_role_assignable_group_membership_changed(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Add member to group.")
	return sel_selection

}

func ruleMatch_safe_attachments_policy_disabled(ev map[string]string) bool {
	sel_selection := (ev["unmapped.EnableSafeAttachments"] == "False") &&
		(ev["metadata.operation"] == "Set-AtpPolicyForO365")
	return sel_selection

}

func ruleMatch_service_principal_credential_added(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Add service principal credentials.")
	return sel_selection

}

func ruleMatch_sharepoint_anonymous_link_created(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "AnonymousLinkCreated")
	return sel_selection

}

func ruleMatch_sharepoint_external_user_granted_access(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "SharingSet") &&
		(ev["unmapped.TargetUserOrGroupType"] == "Guest")
	return sel_selection

}

func ruleMatch_sharepoint_site_collection_admin_added(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Add site collection admin.")
	return sel_selection

}

func ruleMatch_sharepoint_site_permission_broadened(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "PermissionLevelModified")
	return sel_selection

}

func ruleMatch_tenant_audit_log_disabled(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Set-AdminAuditLogConfig") &&
		(ev["unmapped.UnifiedAuditLogIngestionEnabled"] == "False")
	return sel_selection

}

func ruleMatch_transport_rule_forwards_externally(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "New-TransportRule")
	return sel_selection

}

func ruleMatch_trusted_location_added_to_conditional_access(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Add a named location.")
	return sel_selection

}
