// Code generated by sigmac-gen from detections/rules and detections/fixtures. DO NOT EDIT.

package detectgen

import (
	"strings"
)

type CompiledRule struct {
	ID       string
	Title    string
	Level    string
	MitreIDs []string
	Engine   string
	Matches  func(ev map[string]string) bool
}

var Rules = []CompiledRule{
	{ID: "8f1a2b3c-0001-4a00-9000-000000000005", Title: "Sign-in through a known anonymiser or proxy", Level: "high", MitreIDs: []string{"attack.t1090.003"}, Engine: "in-stream", Matches: ruleMatch_anonymous_proxy_signin},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000008", Title: "Impossible travel between sign-ins", Level: "high", MitreIDs: []string{"attack.t1078.004"}, Engine: "windowed", Matches: ruleMatch_impossible_travel},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000007", Title: "Mass file download or deletion within a short window", Level: "high", MitreIDs: []string{"attack.t1530"}, Engine: "windowed", Matches: ruleMatch_mass_file_download},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000006", Title: "Mass mailbox item access within a short window", Level: "high", MitreIDs: []string{"attack.t1114.002"}, Engine: "windowed", Matches: ruleMatch_mass_mailbox_download},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000004", Title: "MFA method registration outside business hours", Level: "medium", MitreIDs: []string{"attack.t1556.006"}, Engine: "in-stream", Matches: ruleMatch_mfa_method_registration},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000001", Title: "New inbox forwarding rule to an external address", Level: "medium", MitreIDs: []string{"attack.t1114.003"}, Engine: "in-stream", Matches: ruleMatch_new_inbox_forwarding_rule},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000002", Title: "OAuth consent grant to an unverified application", Level: "high", MitreIDs: []string{"attack.t1528"}, Engine: "in-stream", Matches: ruleMatch_oauth_consent_unverified_app},
	{ID: "8f1a2b3c-0001-4a00-9000-000000000003", Title: "Privileged directory role assignment", Level: "medium", MitreIDs: []string{"attack.t1098.003"}, Engine: "in-stream", Matches: ruleMatch_privileged_role_assignment},
}

func boolToInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

func ruleMatch_anonymous_proxy_signin(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "UserLoggedIn") &&
		(ev["unmapped.ResultStatus"] == "Success")
	return sel_selection

}

func ruleMatch_impossible_travel(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "UserLoggedIn") &&
		(ev["unmapped.ResultStatus"] == "Success")
	return sel_selection

}

func ruleMatch_mass_file_download(ev map[string]string) bool {
	sel_selection1 := (ev["metadata.operation"] == "FileDownloaded")
	sel_selection2 := (ev["metadata.operation"] == "FileDeleted")
	return (sel_selection1 || sel_selection2)

}

func ruleMatch_mass_mailbox_download(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "MailItemsAccessed")
	return sel_selection

}

func ruleMatch_mfa_method_registration(ev map[string]string) bool {
	sel_selection := (strings.HasPrefix(ev["metadata.operation"], "Register security info"))
	return sel_selection

}

func ruleMatch_new_inbox_forwarding_rule(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "New-InboxRule")
	return sel_selection

}

func ruleMatch_oauth_consent_unverified_app(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Consent to application.")
	return sel_selection

}

func ruleMatch_privileged_role_assignment(ev map[string]string) bool {
	sel_selection := (ev["metadata.operation"] == "Add member to role.")
	return sel_selection

}
