// Code generated by packages/schema/scripts/generate-go.mjs. DO NOT EDIT.
//
// Source of truth: packages/schema/src/index.ts. Edit that file and run
// `pnpm --filter @sentinel/schema generate`; an edit here is discarded on
// the next run, and it cannot change what the TypeScript side believes the
// contract is — which means an edit here that looks correct is strictly
// worse than no edit at all.

package sentinelschema

// SchemaVersion mirrors SCHEMA_VERSION in packages/schema/src/index.ts.
const SchemaVersion = "0.1.0"

// Severity — generated from the TypeScript union of the same name.
type Severity string

const (
	SeverityCritical Severity = "critical"
	SeverityHigh     Severity = "high"
	SeverityMedium   Severity = "medium"
	SeverityLow      Severity = "low"
	SeverityInfo     Severity = "info"
)

// CaseState — generated from the TypeScript union of the same name.
type CaseState string

const (
	CaseStateOpen             CaseState = "open"
	CaseStateTriaging         CaseState = "triaging"
	CaseStateInvestigating    CaseState = "investigating"
	CaseStateAwaitingApproval CaseState = "awaiting_approval"
	CaseStateActioned         CaseState = "actioned"
	CaseStateClosed           CaseState = "closed"
	CaseStateDismissed        CaseState = "dismissed"
)

// Urgency — generated from the TypeScript union of the same name.
type Urgency string

const (
	UrgencyNow   Urgency = "now"
	UrgencyToday Urgency = "today"
	UrgencyLater Urgency = "later"
)

// Claim — generated from the TypeScript interface of the same name.
type Claim struct {
	Text        string   `json:"text"`
	EvidenceRef []string `json:"evidenceRef"`
}

// Verdict — generated from the TypeScript interface of the same name.
type Verdict struct {
	Severity           Severity            `json:"severity"`
	Title              string              `json:"title"`
	Claims             []Claim             `json:"claims"`
	AttackChain        []string            `json:"attackChain"`
	RecommendedActions []RecommendedAction `json:"recommendedActions"`
}

// RecommendedAction — generated from the TypeScript interface of the same name.
type RecommendedAction struct {
	Playbook    string  `json:"playbook"`
	Urgency     Urgency `json:"urgency"`
	BlastRadius string  `json:"blastRadius"`
}
