#!/usr/bin/env node
/**
 * Generates Go structs from src/index.ts (P0-11 AC2). Not hand-written —
 * src/index.ts is the one source of truth (AC1); this script is the only
 * thing that writes go/sentinelschema/schema.gen.go.
 *
 *   node scripts/generate-go.mjs            regenerate
 *   node scripts/generate-go.mjs --check     fail if committed output is stale (AC3, T1)
 */
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { parseSchema } from './parse-schema.mjs';

/** Pipes generated source through `gofmt`, so the committed file is always
 * canonically formatted — this generator's own struct-literal construction
 * does not align fields the way `gofmt` does, and a generated .go file that
 * `gofmt -l` flags is exactly the kind of thing golangci-lint's own gofmt
 * check (already run in ci-go.yml) would catch, just later and less clearly
 * than failing here. */
function gofmt(source) {
  const result = spawnSync('gofmt', [], { input: source, encoding: 'utf8' });
  if (result.error || result.status !== 0) {
    throw new Error(
      `generate-go: gofmt failed (is Go on PATH?)\n${result.stderr ?? result.error?.message ?? ''}`,
    );
  }
  return result.stdout;
}

const PKG_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const REPO_ROOT = join(PKG_ROOT, '..', '..');
const SOURCE = join(PKG_ROOT, 'src', 'index.ts');
const OUT = join(REPO_ROOT, 'go', 'sentinelschema', 'schema.gen.go');
const CHECK = process.argv.includes('--check');

const BANNER = `// Code generated by packages/schema/scripts/generate-go.mjs. DO NOT EDIT.
//
// Source of truth: packages/schema/src/index.ts. Edit that file and run
// \`pnpm --filter @sentinel/schema generate\`; an edit here is discarded on
// the next run, and it cannot change what the TypeScript side believes the
// contract is — which means an edit here that looks correct is strictly
// worse than no edit at all.

package sentinelschema
`;

function pascalCase(name) {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

/** snake_case or camelCase field name -> the JSON tag the TS side actually
 * emits with plain JSON.stringify (camelCase, unchanged) — so the Go tag
 * matches what is really on the wire, not a guessed convention. */
function jsonTagFor(fieldName) {
  return fieldName;
}

function goFieldName(fieldName) {
  // Go exported fields are PascalCase; everything here is exported because
  // encoding/json cannot see unexported fields at all.
  return pascalCase(fieldName.replace(/_([a-z])/g, (_, c) => c.toUpperCase()));
}

function goTypeOf(type, unions) {
  switch (type.kind) {
    case 'string':
      return 'string';
    case 'number':
      // float64, not int: TypeScript's `number` has no integer/float
      // distinction, so the Go side cannot assume integer-only values
      // without the TS source saying so some other way than `number`.
      return 'float64';
    case 'boolean':
      return 'bool';
    case 'array':
      return `[]${goTypeOf(type.of, unions)}`;
    case 'ref':
      // A reference to a string-literal union becomes a named Go string
      // type (see emitUnion); a reference to an interface becomes a Go
      // struct of the same name — both already PascalCase, matching Go's
      // own exported-identifier convention, which TypeScript interface
      // names already happen to follow in this file.
      return type.name;
    default:
      throw new Error(`generate-go: unhandled type kind "${type.kind}"`);
  }
}

function emitUnion(name, values) {
  const lines = [`// ${name} — generated from the TypeScript union of the same name.`];
  lines.push(`type ${name} string`);
  lines.push('');
  lines.push('const (');
  for (const v of values) {
    const constName = `${name}${pascalCase(v.replace(/_([a-z])/g, (_, c) => c.toUpperCase()))}`;
    lines.push(`\t${constName} ${name} = ${JSON.stringify(v)}`);
  }
  lines.push(')');
  return lines.join('\n');
}

function emitInterface(name, fields, unions) {
  const lines = [`// ${name} — generated from the TypeScript interface of the same name.`];
  lines.push(`type ${name} struct {`);
  for (const f of fields) {
    const goType = goTypeOf(f.type, unions);
    // Optional fields are pointers, not a bare value with omitempty: a
    // pointer distinguishes "this field was absent" from "this field was
    // present with the zero value" (false, 0, ""), which omitempty alone on
    // a non-pointer cannot — a false boolean and a missing boolean would
    // otherwise be indistinguishable once this struct round-trips.
    const fieldType = f.optional ? `*${goType}` : goType;
    const tag = f.optional ? `${jsonTagFor(f.name)},omitempty` : jsonTagFor(f.name);
    lines.push(`\t${goFieldName(f.name)} ${fieldType} \`json:"${tag}"\``);
  }
  lines.push('}');
  return lines.join('\n');
}

const schema = parseSchema(SOURCE);

const sections = [
  `// SchemaVersion mirrors SCHEMA_VERSION in packages/schema/src/index.ts.`,
  `const SchemaVersion = ${JSON.stringify(schema.version)}`,
  '',
];

for (const [name, values] of Object.entries(schema.unions)) {
  sections.push(emitUnion(name, values), '');
}
for (const [name, iface] of Object.entries(schema.interfaces)) {
  sections.push(emitInterface(name, iface.fields, schema.unions), '');
}

const output = gofmt(`${BANNER}\n${sections.join('\n')}`);

if (CHECK) {
  if (!existsSync(OUT)) {
    console.error(`generate-go --check: ${OUT} does not exist. Run: pnpm --filter @sentinel/schema generate`);
    process.exit(1);
  }
  const committed = readFileSync(OUT, 'utf8');
  if (committed !== output) {
    console.error(
      'generate-go --check: go/sentinelschema/schema.gen.go is out of date.\n' +
        '  src/index.ts changed without regenerating. Run: pnpm --filter @sentinel/schema generate',
    );
    process.exit(1);
  }
  console.log('generate-go --check: up to date');
  process.exit(0);
}

writeFileSync(OUT, output, 'utf8');
console.log(`generate-go: wrote ${OUT}`);
