package attck

import (
	"fmt"
	"strings"
)

// NavigatorLayerVersion/NavigatorMinAppVersion are the ATT&CK Navigator
// layer file format's own version fields (layers/spec/v4.5/
// layerformat.md in mitre-attack/attack-navigator, pinned the same way
// CatalogueVersion pins the technique data itself) — "layer" must be
// exactly "4.5"; "navigator" must be at least "4.9.0" per that spec's
// own Version object table.
const (
	NavigatorLayerVersion  = "4.5"
	NavigatorMinAppVersion = "4.9.0"
)

// Layer is the subset of the Navigator layer file format this package
// actually populates — every field below is either required by the
// spec (name, domain, versions.navigator, versions.layer) or used to
// render coverage (techniques, legendItems). Optional cosmetic fields
// the spec defines (filters, layout, sorting, gradient, ...) are left
// at the Navigator's own documented defaults rather than restated here.
type Layer struct {
	Name        string            `json:"name"`
	Description string            `json:"description"`
	Versions    LayerVersions     `json:"versions"`
	Domain      string            `json:"domain"`
	Techniques  []LayerTechnique  `json:"techniques"`
	LegendItems []LayerLegendItem `json:"legendItems"`
}

type LayerVersions struct {
	Attack    string `json:"attack"`
	Navigator string `json:"navigator"`
	Layer     string `json:"layer"`
}

type LayerTechnique struct {
	TechniqueID string `json:"techniqueID"`
	Color       string `json:"color,omitempty"`
	Comment     string `json:"comment,omitempty"`
}

type LayerLegendItem struct {
	Label string `json:"label"`
	Color string `json:"color"`
}

const (
	colorCovered   = "#4caf50" // green
	colorUncovered = "#e0e0e0" // grey
)

// BuildNavigatorLayer renders a Report as a Navigator layer — AC4,
// "coverage is rendered as a navigator-compatible layer for
// stakeholders". Every current (non-deprecated, non-revoked) technique
// in the pinned catalogue gets an entry, covered or not, so a
// stakeholder opening this in the real Navigator sees gaps directly on
// the matrix rather than having to infer them from absence.
func BuildNavigatorLayer(report Report) *Layer {
	layer := &Layer{
		Name:        "Sentinel detection coverage",
		Description: fmt.Sprintf("Rule coverage against ATT&CK %s — generated by services/detect/cmd/sigmac-gen, not hand-edited.", strings.TrimPrefix(CatalogueVersion, "v")),
		Versions: LayerVersions{
			Attack:    strings.TrimPrefix(CatalogueVersion, "v"),
			Navigator: NavigatorMinAppVersion,
			Layer:     NavigatorLayerVersion,
		},
		Domain: "enterprise-attack",
		LegendItems: []LayerLegendItem{
			{Label: "Covered by at least one rule", Color: colorCovered},
			{Label: "Not covered", Color: colorUncovered},
		},
	}
	for _, t := range report.Techniques {
		lt := LayerTechnique{TechniqueID: t.ID}
		if t.Covered {
			lt.Color = colorCovered
			lt.Comment = "Covered by: " + strings.Join(t.RuleTitles, ", ")
		} else {
			lt.Color = colorUncovered
		}
		layer.Techniques = append(layer.Techniques, lt)
	}
	return layer
}

// Validate checks this layer against layerformat.md's own required
// fields — T3's proxy for "loads without error in the real ATT&CK
// Navigator" achievable without a browser: the same structural
// requirements the Navigator's own loader enforces (name and domain
// present; domain one of the three real values; versions.layer exactly
// "4.5"; versions.navigator at least "4.9.0"; every techniqueID a real,
// current catalogue id).
func (l *Layer) Validate() error {
	if strings.TrimSpace(l.Name) == "" {
		return fmt.Errorf("navigator layer: name is required")
	}
	switch l.Domain {
	case "enterprise-attack", "mobile-attack", "ics-attack":
	default:
		return fmt.Errorf("navigator layer: domain %q is not one of enterprise-attack/mobile-attack/ics-attack", l.Domain)
	}
	if l.Versions.Layer != NavigatorLayerVersion {
		return fmt.Errorf("navigator layer: versions.layer = %q, must be exactly %q", l.Versions.Layer, NavigatorLayerVersion)
	}
	if l.Versions.Navigator == "" {
		return fmt.Errorf("navigator layer: versions.navigator is required")
	}
	for _, t := range l.Techniques {
		if strings.TrimSpace(t.TechniqueID) == "" {
			return fmt.Errorf("navigator layer: a technique entry has no techniqueID")
		}
		tech, ok := Lookup(t.TechniqueID)
		if !ok {
			return fmt.Errorf("navigator layer: techniqueID %q is not a known ATT&CK technique", t.TechniqueID)
		}
		if tech.Revoked || tech.Deprecated {
			return fmt.Errorf("navigator layer: techniqueID %q is revoked or deprecated", t.TechniqueID)
		}
	}
	return nil
}
